version: "2.2"
services:
  remote_dev_mmdet:
    shm_size: '8gb'
    runtime: nvidia
    build:
      context: .
      args:
        IMAGE: supervisely/base-py-sdk:6.9.1
    ports:
      - "9788:22"
    volumes:
      - "./data:/data"